import type { NormalizedInputs } from './types';
export const DEFAULT_INPUTS: NormalizedInputs = {
  carPrice: 64200,
  salary: 150000,
  vehicleType: 'BEV',
  annualKm: 8000,
  electricityPrice: 0.3,
  evEfficiency: 17,
  fuelPrice: 1.9,
  fuelEfficiency: 8,
  insurance: 3000,
  insuranceNonGst: 0,
  annualRegistration: 84,
  annualCtp: 632,
  servicing: 200,
  tyres: 0,
  otherRunning: 0,
  interestRate: 11,
  years: 3,
  adminMonthly: 31,
  advancedPrice: false,
  purchaseRegistration: 0,
  stampDuty: 0,
  dealerCharges: 0,
  otherNonGst: 0,
  energyGstEligible: false,
  otherGstEligible: false,
  firstHeldAndUsedDate: '2026-09-12',
  leaseStartDate: '2026-09-12',
  lctPayable: 'no',
  helpDebt: false,
  privateHospitalCover: true,
  familyStatus: 'single',
  dependants: 0,
  spouseIncome: 0,
  upfrontAfterTax: 0,
  endAfterTax: 0,
};
